services:
  postgres:
    image: postgres:15
    container_name: GEDS-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: geds_db
      POSTGRES_USER: geds_user
      POSTGRES_PASSWORD: geds_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

