spring:
  application:
    name: GEDS

  datasource:
    url: jdbc:postgresql://localhost:5432/geds_db
    username: geds_user
    password: geds_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    serialization:
      indent-output: true
    time-zone: UTC

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

